name: octavapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  image_picker: ^1.0.0
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.0+1
  url_launcher: ^6.2.1
  firebase_app_check: ^0.3.2+7
  intl: ^0.20.2
  firebase_messaging: 15.2.7
  flutter_local_notifications: ^19.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3 

flutter:
  uses-material-design: true

  assets:
    - assets/images/b8.png
    - assets/images/h8.png
    - assets/images/f8.png
    - assets/images/escudo.png
    - assets/images/atrasb8.png
    - assets/images/frenteb8.png
    - assets/images/ladob8.png
    - assets/images/volteadob8.png
    - assets/icon.png   

flutter_icons:  
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"
